name: Content report
description: Please use this issue to report any content that is not in the KB yet, but should be.
title: "[Content]: "
body:

body:
- type: input
  id: title
  attributes:
    label: Tittle of the document
    description: Please insert here the title of the document.
  validations:
    required: true
- type: input
  id: metadata
  attributes:
    label: Metadata
    description: Please insert here, if available, the metadata url of the document.
  validations:
    required: false
 - type: input
  id: metadata
  attributes:
    label: Metadata
    description: Please insert here, if available, the metadata url of the document.
    validations: 
     required: false
- type: input
  id: url
  attributes:
    label: url
    description: Please provide the url or other identifier for the document.
  validations:
    required: true
