
name: Content Upload
description: File a content report
body:
  
  - type: input
    id: title
    attributes:
      label: Title of document
      description: "Title of document"
    validations:
      required: true  
  - type: input
    id: url
    attributes:
      label: Url or DOI where the document can be found
      description: "Please provide the full url of your content to be uploaded."
     
    validations:
      required: false
  - type: input
    id: noUrl    
    attributes:
      label: If not associated, where the document can be found?
      description: "If the document is not associated with any url, please let us know how we can access the file to be uploaded."
     
    validations:
      required: false     
  - type: input
    id: keyword
    attributes:
      label: Keyword
      description: "Please provide the keywords for this document. They must be separated by a semi-colon."
     
    validations:
      required: false
   - type: dropdown
  id: download
  attributes:
    label: Who can access the document?
    options:
      - Public
      - Private
  validations:
    required: true    
  - type: input
    id: metadata
    attributes:
      label: Metadata Link
      description: "Please provide, if available, the url to the metadata."
     
   
 
 

