
name: Content to be uploaded
description: Content to be uploaded
title: "[Bug]: "
labels: [Content to be uploaded]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this content report!
  - type: input
    id: title
    attributes:
      label: Title of the document
      description: "Title of the document"
    validations:
      required: true 
  - type: input
    id: url
    attributes:
      label: url where the document can be found-
      description: "Please provide the full url of your content to be uploaded" 
    validations:
      required: true  
