
name: Content Upload
description: File a content report
body:
  - type: dropdown
  id: download
  attributes:
    label: How did you download the software?
    options:
      - Homebrew
      - MacPorts
      - apt-get
      - Built from source
  validations:
    required: true
  - type: input
    id: title
    attributes:
      label: Title of document
      description: "Title of document"
    validations:
      required: true  
  - type: input
    id: url
    attributes:
      label: Url where the document can be found
      description: "Please provide the full url of your content to be uploaded."
     
    validations:
      required: false
  - type: input
    id: noUrl    
    attributes:
      label: Where the document can be found
      description: "If the document is not associated with any url, please let us know how we can access the file to be uploaded."
     
    validations:
      required: false     
  - type: input
    id: keyword
    attributes:
      label: Keyword
      description: "Please provide the keywords for this document. They must be separated by a semi-colon."
     
    validations:
      required: false
      
  - type: input
    id: metadata
    attributes:
      label: Metadata Link
      description: "Please provide, if available, the url to the metadata."
     
   
 
 

