name: Content Upload
description: If you have any content that should be in the DiSSCo KB and it is not, please use this issue to let us know.
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this content report!
- type: input
  id: title
  attributes:
    label: The title of the document
    description: Please insert the title of the document
  validations:
    required: true
- type: input
  id: url
  attributes:
    label: url
    description: Please provide the url or other identifier for the content
  validations:
    required: true
    - type: input
  id: metadata
  attributes:
    label: metadata
    description: Please provide the metadata url, if available.
  validations:
    required: false

