name: Content upload
description: Content upload
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this content report!
- type: input
  id: title
  attributes:
    label: The title of the document
    description: Please insert the title of the document
  validations:
    required: true
- type: input
  id: url
  attributes:
    label: url
    description: Please provide the url or other identifier for the content
  validations:
    required: true

